apiVersion: batch/v1
kind: Job
metadata:
  name: k6
  namespace: k6
  # annotations:
  #   sidecar.istio.io/rewriteAppHTTPProbers: "true"
  labels:
    group: test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: loadimpact/k6:0.27.1
        args:
          - run
          - /k6-script.js
          # command: [ "k6", "run", "--vus", "30", "--duration", "20s", "/tmp/script.js" ]
        volumeMounts:
        - name: k6-script
          mountPath: /k6-script.js
          subPath: k6-script.js
      restartPolicy: Never
      volumes:
      - name: "k6-script"
        configMap:
          name: "k6-script"